name: CD

on:
  workflow_run:
    workflows: [CI]
    branches: [main, webpack_css_fix]
    types: [completed]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "ğŸ”§ setup node"
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Setup .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SEMANTIC_SCHOLAR_API_KEY: ${{ secrets.SEMANTIC_SCHOLAR_API_KEY }}
          directory: ./
          file_name: .env
          fail_on_empty: true

      - name: Install and Build ğŸ”§
        run: |
          npm install
          npm run build
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: build # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
