name: CI

on: 
  push:

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v3.0.2

      - name: "ğŸ”§ setup node"
        uses: actions/setup-node@v3.5.1
        with:
            node-version: "16"
            
      - name: "ğŸ“¦ install dependencies"
        run: npm install

      - name: "ğŸ§  doing some brain things"
        run: npm test

      - name: "ğŸ˜¶â€ğŸŒ«ï¸ linter prettier"
        run: npm run lint
