name: CI

on: 
  workflow_call:  
  push:
        branches: [PL-11-Setup-CI-pipeline, main]
jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v3.0.2

      - name: "ğŸ”§ setup node"
        uses: actions/setup-node@v3.5.1

      - name: "ğŸ”§ install npm@latest"
        run: npm i -g npm@latest

      - name: "ğŸ“¦ install dependencies"
        run: npm install

      - name: "ğŸ§  doing some brain things"
        run: npm test

      - name: "ğŸ˜¶â€ğŸŒ«ï¸ linter prettier"
        run: npm run lint
