name: CI

on:
  push:

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v3.0.2

      - name: "ğŸ”§ setup node"
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "18"

      - name: "ğŸ“¦ install dependencies"
        run: npm install

      - name: Setup .env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_SECRET_KEY: ${{ secrets.SEMANTIC_SCHOLAR_API_KEY }}
        directory: ./
        file_name: .env
        fail_on_empty: true

      - name: "ğŸ§  run unit tests"
        run: npm test

      - name: "ğŸ˜¶â€ğŸŒ«ï¸ linter prettier"
        run: npm run lint
