name: CI

on:
  push:
    branches: [PL-11-Setup-CI-pipeline]

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v3.2.0

      - name: "ğŸ”§ setup node"
        uses: actions/setup-node@v3.5.1

      - name: "ğŸ”§ install npm@latest"
        run: npm i -g npm@latest

      - name: "ğŸ“¦ install dependencies"
        run: npm install
      
      - name: "ğŸ§  doing some brain things"
        run: npm test
        
      - name: "ğŸ˜¶â€ğŸŒ«ï¸ cleaning the code"
        run: npm run formatting
        
      

